### ISSUE TITLE
Searching with latitude & longitude

### ISSUE THREAD

**Issue by Targun** [olalonde/node-yelp#10]
Tried with type string and type number:
yelp.search({term: "restaurants", location: "chicago", latitude: "41.900144", longitude: "-87.639887"}, cb);

also tried:
yelp.search({term: "restaurants", location: "chicago", cll: "41.900144,-87.639887"}, cb);

**Comment by olalonde** [comment]
Is that supported by their API? If so can you link to their documentation. It should be working though as I haven't restricted what query params can be passed to the methods.

**Comment by mittonk** [comment]
* https://www.yelp.com/developers/documentation/v2/search_api

@Targun , I think you've got the choice between:
1. "location" (like "Paris") with optional "cll" for disambiguation (mostly, "which 'Paris' --- France or Texas?"
2. "ll", to do latitude & longitude.  It sounds like this is what you want.
3. "bounds" for finer control of lat-long and zoom level.

You don't say what you see wrong --- are you getting an error like "UNSPECIFIED_LOCATION" or just different locations than you expect?

**Comment by Targun** [comment]
Thanks for your comments. Not the most elegant, but this did the trick:

https://github.com/Targun/node-yelp/commit/3778263599dd09eaba496a66f3d617e04a623857
