### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by nguyenquynhan** [olalonde/node-yelp#14]
I run on window don't have error, but when I deploy code to linux, library get error: Promise is not defined.
Detail error:
ReferenceError: Promise is not defined
at Yelp.get (/home/centos/apps/AskFoodie/Seed Service/node_modules/yelp/lib/index.js:42:25)
at Yelp.search (/home/centos/apps/AskFoodie/Seed Service/node_modules/yelp/lib/index.js:64:19)

Please help me resolve this issue! Thanks!

**Comment by olalonde** [comment]
Hi @nguyenquynhan. Can you upgrade your node version? I believe promises were introduced in node >=0.10. Otherwise, you will need to use a promise polyfill, e.g: https://github.com/jakearchibald/es6-promise#auto-polyfill
