### ISSUE TITLE
how to call the api with longitude and latitude

### ISSUE THREAD

**Issue by rushlinneu** [olalonde/node-yelp#15]
https://api.yelp.com/v2/search?term=german+food&location=Hayes&cll=37.77493,-122.419415

with yelp api above, how can we call the yelp.search, thanks a lot.

**Comment by davidchang** [comment]
```
yelp.search({ term : 'german food', location : 'Hayes', cll : '37.77493,-122.419415' })
```

**Comment by freeslugs** [comment]
or this:  `yelp.search({ term: "chipotle", ll: "40.748068,-73.985056"})`
