### ISSUE TITLE
UNMET PEER DEPENDANCY

### ISSUE THREAD

**Issue by truthstands** [olalonde/node-yelp#17]
My project is built on meanjs boilerplate. When I run, `npm install --save yelp`. I get the following results:

`UNMET PEER DEPENDENCY eslint-plugin-react@^4.0.0
├── generator-angular@0.15.1  extraneous
└── UNMET PEER DEPENDENCY generator-karma@>=0.9.0`

What is the best way to resolve this?

**Comment by olalonde** [comment]
I believe those warning messages will show up if you install any npm module. You should open an issue with meanjs.

**Comment by truthstands** [comment]
Thanks, will do.
