### ISSUE TITLE
how to retrieve data more than 1000?

### ISSUE THREAD

**Issue by swizardlv** [olalonde/node-yelp#18]
Hi , I try to retrieve business data using node-yelp yelp.search() , the total amount of the business is 5000. I specify a parameter offset in a loop to try to retrieve all the data. I got error that the maximum  of offset is 1000.

Is there a way to let me get the data from 10001 to 5000?

May thanks.

**Comment by olalonde** [comment]
That's probably a limitation of Yelp's API, not this module.
