### ISSUE TITLE
Getting same results for locations regardless of any terms used to query

### ISSUE THREAD

**Issue by omenocal** [olalonde/node-yelp#19]
Hello, I'm not sure if this an issue from the Git project or the Yelp API. I started using this library from the NPM. I put my credentials and queries results are fine. However, no matter the term I set, I always get the same results for a location. For example:

- If I look for food, or sports in Chicago I always get the same first 20 results.
- If I look for hospitals, or hotels in Kentucky I always get the same first 20 results (this time a set of results different from the Chicago query).

My code is really simple:

For dependencies
`"dependencies": {
    "yelp": "1.0.1"
  },`

And JavaScript code:
```
var Yelp = require("yelp");
var yelpClient = new Yelp({
  consumer_key: 'xxxxxxxxxxxxxxxxxxxx',
  consumer_secret: 'xxxxxxxxxxxxxxxxxxx',
  token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  token_secret: 'xxxxxxxxxxxxxxxxxxxx',
});

yelpClient.search({
            terms: item,
            location: itemLocation
        }).then(function (data) {
            var businesses = data.businesses;
```

**Comment by olalonde** [comment]
It's `term` not `terms` I think.

**Comment by mittonk** [comment]
Yes, `term`:
* https://www.yelp.com/developers/documentation/v2/search_api
