### ISSUE TITLE
oauth token error?

### ISSUE THREAD

**Issue by swyxio** [olalonde/node-yelp#24]
```
{
  "statusCode": 400,
  "data": "{\"error\": {\"text\": \"One or more parameters are missing in request\", \"id\": \"MISSING_PARAMETER\", \"field\": \"oauth_token\"}}"
}
```

**Comment by rayarikar** [comment]
i am getting the same error. Sample code below

var yelp = new Yelp({
    consumer_key: yelpApiKeyDetails.CONSUMER_KEY,
    consumer_secret: yelpApiKeyDetails.CONSUMER_SECRET_KEY,
    token: yelpApiKeyDetails.TOKEN,
    token_secret: yelpApiKeyDetails.TOKEN_SECRET,
});

let searchYelpWithoutParams = () => {
    yelp.search({term: 'food', location: 'Montreal'})
        .then(function (data) {
            console.log("Received:\n");
            console.log(data);
        })
        .catch(function (err) {
            console.error(err);
        });
};

**Comment by olalonde** [comment]
Does `console.log(yelpApiKeyDetails)` return all the proper strings?

**Comment by swyxio** [comment]
I'm going to proactively close this as I tried out yelp-api-v3 and it worked out of the box.. not sure if it is because the api version moved.
